### ISSUE TITLE
Bugs with recipes' ingredients not showing up and missing tooltips' additions

### ISSUE THREAD

**Issue by Surfingnet** [TLDRMissions/UnlearnedRecipes#3]
After installing the addon, I started having 2 issues:

1. when I click some recipes (which are already learnt) the ingredients needed don't show up sometimes. It does not happen everytime and usually clicking again on the recipe a few times makes the ingredients appear again.
2. I use to have some additional data in the tooltips of both the ingredients and the final product of a recipe (such as the amount of it stored in my bank (given by Syndicator), and more) but now it's only the default tooltip.

Without the addon, the crafting window and the recipes and ingredients tooltips have no issue.

Playing on Classic Era. Installed with Curseforge.

**Comment by teelolws** [comment]
Don't know why its not showing you Syndicator info, works for me:

![image](https://github.com/TLDRMissions/UnlearnedRecipes/assets/49792789/03544f61-0858-4e79-9014-a716b99e7ae8)

**Comment by Surfingnet** [comment]
It's working again for me now.
